version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # image: bezuro/rnc-delete-large-data:latest
    # ports:
    #   - '80:80'
    volumes:
      - .:/var/www/html
      - /var/www/html/vendor/
    environment:
      DB_CONNECTION: mysql
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USERNAME: laravel
      DB_DATABASE: laravel
      DB_PASSWORD: 1337
    depends_on:
      - mysql
    networks:
      - app-network

  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - app-network

  mysql:
    image: mysql:latest
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'laravel'
      MYSQL_PASSWORD: '1337'
      MYSQL_ROOT_PASSWORD: '1337'
    networks:
      - app-network

  phpmyadmin:
    depends_on:
      - mysql
    image: phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
    driver: local
